### PR TITLE
Changed debug into trace for packet logs

### PR DESCRIPTION
**Pull request by WoLfulus**
## :memo: Description

Related to #321

### CODE REVIEW

**Comment by icebob** [comment]
The `console.trace` prints stack traces too for every message... It's not too good.
image
Maybe need to change the logger that it uses `console.debug` for `trace` messages too.

**Comment by WoLfulus** [comment]
I'll take a better look at this ASAP

**Comment by ryanm-pm** [comment]
A verbosity setting could be a good solution to this. Leave it in the debug level but add a verbosity input to the logger function with a default of 1. If the level is set higher in the broker settings, include those of a higher number.

**Comment by WoLfulus** [comment]
i havent had time to take a proper look at this again :(

**Comment by icebob** [comment]
Other PR will be merged #373 instead of this. Sorry.

**Pull request closed without merging**
