### PR TITLE
Add support for redis cluster cacher

### PR DESCRIPTION
**Pull request by Gadi-Manor**
## :memo: Description

Add support for redis cluster cacher.

### :dart: Relevant issues
#509

### :gem: Type of change
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by icebob** [comment]
Thanks, please add relevant tests, as well.

**Comment by icebob** [comment]
@Gadi-Manor will you continue based on this? https://github.com/moleculerjs/moleculer/issues/509#issuecomment-494453146

**Comment by Gadi-Manor** [comment]
@icebob, yes.
I just hope I'll find the time to do it soon.

**Comment by Gadi-Manor** [comment]
@icebob, Do you know why continuous-integration/travis-ci/pr failed?

**Comment by icebob** [comment]
I don't know. I've restarted and now it works.

**Comment by icebob** [comment]
Are you done?

**Comment by Gadi-Manor** [comment]
Yeah, unless you have any comments.

**Comment by icebob** [comment]
No, It looks good. I'm merging... Thank you for your work!

**Comment by Gadi-Manor** [comment]
My pleasure :)

**Comment by Gadi-Manor** [comment]
Is there a reason why the latest publish doesn't include the changes?

**Comment by icebob** [comment]
It is in master, 0.14 are in next branch and it seems I forget to update next from master. I will do it & release beta2, too.

**Comment by icebob** [comment]
I've checked, but the yesterday release contains this PR.

**Comment by Gadi-Manor** [comment]
My bad, I didn't know I was supposed to install from the `next` branch.

**Pull request closed without merging**
