### PR TITLE
fix(typescript) updated check retryable error param type to moleculer error

### PR DESCRIPTION
**Pull request by alvarocantador**
## :memo: Description

Updated the CheckRetryable error param type to follow the real object structure and also what is described in the documentation:

```
...
check: err => err && !!err.retryable
...
```

The `retryable` property is only available in the `Errors.MoleculerError` type.

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by shawnmcknight** [comment]
Please see this [comment](https://github.com/moleculerjs/moleculer/pull/1068#discussion_r828423923) from an earlier declined PR.  The retry middleware has to be capable of handling any error type as there is no guarantee that the error will be an instance of `Moleculer.Error`.

Since an attempt to change this has been submitted 2x now, I'm assuming people are having an issue making their own implementation of this check with the existing typings.  I did a quick test and with the type being `Error` alone it's not able to access the `retryable` property in an implementation.  I think the correct solution here is therefore:

```
type CheckRetryable = (err: Errors.MoleculerError | Error) => boolean;
```

An implementation can then narrow the type to access the retryable property without getting type errors:
```
const retry: CheckRetryable = (err) => {
    return err != null && 'retryable' in err && err.retryable;
}
```

**Review by shawnmcknight — CHANGES_REQUESTED** [review]
I think the correct solution here has to be a union of `Errors.MoleculerError` and `Error`.

**Comment by alvarocantador** [comment]
@shawnmcknight I agree with the type union, and not only the  `retryable` property but the `data` and `code` properties are also not available in the default `Error` type.

**Review by shawnmcknight — APPROVED** [review]
LGTM!

**Pull request merged**
