### PR TITLE
fix: Update default type for ServiceSchema generic to Service<S>.

### LINKED ISSUE #1297: New type for ServiceSchema breaks ServiceBroker.createService and interface Options
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Due to recent changes in Typescript definition of ServiceSchema our code fails with tsc for `options.started` and `options.stopped`.
AFAICT, I need to expand ServiceSchema with a "ServiceThis". When I (try) to do this (I'm unfortunately no Typescript expert), tsc fails for ServiceBroker.createService since it does not accept any other "ServiceThis" as void. There is no way to specify any other type.
The same applies to interface `Options` (when explicitely used as type), if I'm not mistaken.

Besides, I'm really astonished how such a breaking change went into a patch release. At least, instead of `void` it probably would be a better choice to use `Service` as default type for ServiceThis.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.34

### PR DESCRIPTION
**Pull request by marceliwac**
## :memo: Description

Fix for the default type for ServiceSchema generic which was previously set to `void`, causing problems when `This` type was not provided. The type should have defaulted to `Service<S>`.

### :dart: Relevant issues

Fixes #1297.

Original PR which introduced the problem #1272.

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### :scroll: Example code

Given this example setup:
```ts
interface GreeterSettings extends ServiceSettingSchema {
        defaultName: string;
}

interface GreeterMethods {
        uppercase(str: string): string;
        other(): void;
}

interface GreeterLocalVars {
        myVar: string;
}

type GreeterThis = Service<GreeterSettings> & GreeterMethods & GreeterLocalVars;
```

This used to be causing the problems for the following cases:
```ts
// Without providing types for ServiceSchema at all
const GreeterService: ServiceSchema = {
        // ...
}

// Without providing `T` generic, default of `void` for "This" type caused problems.
const GreeterService: ServiceSchema<GreeterSettings> = {
        // ...
}
```

While the following was the only working use-case:
```ts
// Explicitly providing T generic worked as expected
const GreeterService: ServiceSchema<GreeterSettings, GreeterThis> = {
        // ...
}
``` 

Applying this patch fixes the problem for following cases:
```ts
// Without providing types for ServiceSchema at all
const GreeterService: ServiceSchema = {
        // ...
}

// Without providing `T` generic, default of `Service<S>` allows for the code to work as expected.
const GreeterService: ServiceSchema<GreeterSettings> = {
        // ...
}

// Explicitly providing T generic worked as expected
const GreeterService: ServiceSchema<GreeterSettings, GreeterThis> = {
        // ...
}
``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally against TypeScript compiler (version 4.9.4).
- [x] Tested locally against tsd (version 0.22.0).
- [x] Added unit tests that verify the types set for lifecycle handlers in different scenarios (when schema provides setting type, schema provides setting type and this type, schema provides no type).

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by MichaelErmer** [comment]
Any updates on this? 🤔

**Comment by marceliwac** [comment]
I think it's up to the maintainers to merge this now. I suppose given the discussions in #1272 and #1297 @icebob will probably get around to it when he's got some time.

**Review by icebob — APPROVED** [review]

**Comment by MichaelErmer** [comment]
@icebob any idea when this can be released? we are currently stuck on 0.14.33 😨

**Comment by icebob** [comment]
I waited for somebody to test it in his project after merging and before releasing it, but I haven't received any feedback.

**Comment by icebob** [comment]
I've just released it as 0.14.35

**Pull request merged**
