### PR TITLE
Add stream support in actions response

### PR DESCRIPTION
**Pull request by molobala**
As demanded and since I needed it , I tried to add stream support in action response, I just followed what you explained @icebob in #218   
Please take a look at and get me back

### CODE REVIEW

**Comment by icebob** [comment]
Nice PR. I will check it, but I need more time now.
Otherwise, I don't want to merge it to the master yet. So I will create a new branch for this.

**Comment by icebob** [comment]
Please close this PR and open under the [streams](https://github.com/moleculerjs/moleculer/tree/streams) branch instead of master. Thanks.

**Comment by molobala** [comment]
Good  

I think it will be better too if we could stream in context object  
actually I have some actions that need to work with uploaded files, I did it , but it's not optimal, cause I save file first in local in Gateway API node, then , my Gateway expose public path to the file and send this one to my action that then download the file (much process) 

Thank you!

**Comment by icebob** [comment]
I thinking same things, that we need streams in requests too, not only responses.

**Pull request closed without merging**
