### PR TITLE
Update types for Context, ActionHandler, and Cachers Base

### PR DESCRIPTION
**Pull request by glenn-p-ryan**
## :memo: Description
This PR updates types for `Context` and `ActionHandler` which, as a result, should solve the problem discussed in [PR 600](https://github.com/moleculerjs/moleculer/pull/600). Additionally, the type `defaultKeygen` has been added to the `Cachers` namespace under the `Base` class. This method type for generating the key seems to be missing.

### :dart: Relevant issues
Issue being discussed [here](https://github.com/moleculerjs/moleculer/pull/600)

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## :vertical_traffic_light: How Has This Been Tested?

Overrode types in our current implementation of moleculer and tested for ts errors.

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] **New and existing unit tests pass locally with my changes**

### CODE REVIEW

**Comment by icebob** [comment]
@ipetrovic11 @shawnmcknight please review it.

**Comment by icebob** [comment]
I've checked the source, so in the `defaultKeygen` method, the `params` can be null. But if it's not null, it should be an `object`.So, the d.ts modification is correct, I should update the jsdoc according to it.

**Comment by glenn-p-ryan** [comment]
In the `defaultKeygen` method, does the first condition:
`if(params || meta){...}`
also warrant the need to update the jsdocs for `meta` to possibly be null as well?

**Comment by shawnmcknight** [comment]
> In the `defaultKeygen` method, does the first condition:
> `if(params || meta){...}`
> also warrant the need to update the jsdocs for `meta` to possibly be null as well?

It appears to me that `meta` will default to empty object in the `Context` constructor and will only be mutated if the parent context's `meta` is not loose null or the calling options are not loose null.  That implies to me that there is no way for `meta` is ever be `null` by the time it gets to a called action, so that check seems unneeded and there shouldn't be a need to document `meta` in that fashion.

@icebob Do you agree?

**Comment by icebob** [comment]
Yes, meta can't be null, it's initialized as `{}`. Thanks @glenn-p-ryan

**Pull request merged**
