### PR TITLE
fix(transporters/nats): parse user and password of server urls

### PR DESCRIPTION
**Pull request by savsgio**
## :memo: Description

Now the nats transporter does not parse the user and password from the url, just take and set the server hosts.
This PR fixes that, taking the first user and password found in the servers.

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js
new NatsTransporter("nats://MYUSER:MYPASS@server1:4222");
``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test NatsTransporter connect & disconnect & reconnect -> check connect options servers

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by icebob** [comment]
It means different auth for servers is not available in nats.js? E.g. `"nats://user1:pass1@server1:4222,nats://user2:pass2@server2:4222,nats://user3:pass3@server3:4222"`

**Comment by oliversalzburg** [comment]
Just FYI, I believe this introduced a regression.

Before, it was possible to use `url`+`user`+`pass` to connect to your NATS server. This change removes the authentication information and ultimately kills the entire application.

**Comment by intech** [comment]
In this implementation, we also miss the ability to set a token. I suggest doing this as an additional check, if only user is passed and there is no password, then we use the token.

**Comment by AndreMaz** [comment]
Ups! We're terribly sorry for the inconvenience @oliversalzburg Could you please create a PR with the fix?

**Comment by oliversalzburg** [comment]
Don't worry :) I kinda feel like it was a configuration mistake on our side anyway. The idea is probably to use servers+user+pass _or_ URL with all details included.

Maybe a validation in this regard could help to prevent others from making the same mistake?

**Pull request merged**
