### PR TITLE
Updates hot-reload to use recursive-watch

### PR DESCRIPTION
**Pull request by savearray2**
Due to the removal of recursive file watching, the "recursive-watch" library was added to provide recursive folder watching functionality. Guards were also added to ensure file existence when reloading services.

## :memo: Description

- The dependency "recusive-watch" was added.
- `npm` automatically updated the lockfile to version 2.

### :dart: Relevant issues
https://github.com/moleculerjs/moleculer/issues/810#issue-696280751

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## :vertical_traffic_light: How Has This Been Tested?

image

- Ran through some quick tests by renaming and updating the default test service `math.service.js` (screenshot attached).
- Ran `npm test`, which passed (details below).

```
Test Suites: 140 passed, 140 total
Tests:       4 skipped, 2304 passed, 2308 total
Snapshots:   33 passed, 33 total
Time:        20.669 s, estimated 23 s
```

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by joshmanders — APPROVED** [review]
LGTM 👍

**Comment by savearray2** [comment]
@joshmanders 
I apologize for the sudden update. After running some additional tests, I realized that when renaming an existing watched file (e.g. ```math.service.js``` to ```math.a.service.js```), the application would in the ```watchProjectFiles``` function when trying to watch a file that didn't exist any longer (```watchItem.watcher = fs.watch(fName, (eventType) => {```). As such, I wrote additional code that would remove any files from the watch list that don't exist any longer.

For reference, without the additional code the following happens when trying to rename ```math.service.js``` to ```math.a.service.js```:

```
[2020-12-29T04:37:38.156Z] DEBUG dictionary.local-90945/BROKER: Watching the following project files:
[2020-12-29T04:37:38.156Z] DEBUG dictionary.local-90945/BROKER:   services/test/math.service.js: reload 1 service(s) & 0 other(s).
[2020-12-29T04:37:38.156Z] DEBUG dictionary.local-90945/BROKER:     math
node:internal/fs/watchers:227
    throw error;
    ^

Error: ENOENT: no such file or directory, watch '/Users/akari/cute-etc/moleculer-test/services/test/math.service.js'
    at FSWatcher.<computed> (node:internal/fs/watchers:219:26)
    at Object.watch (node:fs:1577:34)
    at /Users/akari/cute-etc/moleculer/src/middlewares/hot-reload.js:118:27
    at Map.forEach (<anonymous>)
    at watchProjectFiles (/Users/akari/cute-etc/moleculer/src/middlewares/hot-reload.js:106:16)
    at invokeFunc (/Users/akari/cute-etc/moleculer/node_modules/lodash/lodash.js:10359:23)
    at trailingEdge (/Users/akari/cute-etc/moleculer/node_modules/lodash/lodash.js:10408:18)
    at Timeout.timerExpired [as _onTimeout] (/Users/akari/cute-etc/moleculer/node_modules/lodash/lodash.js:10396:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/Users/akari/cute-etc/moleculer-test/services/test/math.service.js',
  filename: '/Users/akari/cute-etc/moleculer-test/services/test/math.service.js'
}
```

Sorry for any confusion!

**Comment by savearray2** [comment]
Okay, I messed with this far longer than I'd like to admit. _If anyone has any input, please feel free to look at the updated code and let me know if there's a better way to do this._

- Due to the multiple watchers on files, there were some race conditions that caused the same file/service to be added to the reload queue more than once. I added a deduplication function.

- Also, with the way the code was written previously, __deleted files did not destroy their counterpart services__. This has been fixed with the latest push.

I've attached a screenshot below showing the ```math.service.js``` file being renamed to ```math.service.a.js```, which destroys the ```math``` service. Then adding it back by renaming the file to ```math.a.service.js```.

image

I think this addresses all outstanding issues, but again, if anyone has any input please let me know.

**Comment by icebob** [comment]
Great, I'm checking...

**Review by icebob — APPROVED** [review]
Great job, thank you! I've tested on Windows. Did you test it on Linux?
Btw, I've reverted the lockfile because NPM 6 couldn't handle it, and regenerated.

**Comment by savearray2** [comment]
@icebob 
I tested on Mac. I'll run a test on Linux now.

**Comment by icebob** [comment]
Ok, I'm waiting for it and if it works, I will merge.

**Comment by savearray2** [comment]
@icebob 
I ran a test on one of my Arch Linux servers.
The code seems to run successfully.

```
Linux 5.4.85-1-ec2-lts #1 SMP Tue, 22 Dec 2020 11:42:33 +0000 x86_64 GNU/Linux
node --version
v15.5.0
```

image

The following commands were run:
```bash
mv math.service.js test/
cd test                
mv math.service.js math.service.a.js
mv math.service.a.js math.a.service.js  
```

Thanks :)

**Comment by icebob** [comment]
Cool, thanks!

**Pull request merged**
