### PR TITLE
Add getServiceList, missing in typescript definitions

### PR DESCRIPTION
**Pull request by HazemKhaled**
## :memo: Description

We are using this function in openapi.json auto-generate

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### :scroll: Example code
```js
this.broker.registry.getServiceList({ withActions: true }).forEach(this.logger.info);
```

### CODE REVIEW

**Comment by icebob** [comment]
Something is wrong with d.ts in Travis.

**Comment by Wallacy** [comment]
I dont think this is the right signature:

```typescript
getServiceList({withActions: bool}): ServiceSchema[]
```

Per action-catalog:
https://github.com/moleculerjs/moleculer/blob/master/src/registry/action-catalog.js#L122

The options param has:
```typescript
{onlyLocal = false, onlyAvailable = false, skipInternal = false, withEndpoints = false}
```

So the best approach is:

```typescript
	interface ActionCatalogListOptions {
		onlyLocal:boolean = false;
		onlyAvailable:boolean = false;
		skipInternal:boolean = false;
		withEndpoints:boolean = false;
	}

	class ServiceRegistry {
		broker: ServiceBroker;
		metrics: MetricRegistry;
		logger: LoggerInstance;

		opts: BrokerRegistryOptions;

		StrategyFactory: BaseStrategy;

		nodes: any;
		services: any;
		actions: any;
		events: any;

		getServiceList(opts?: ActionCatalogListOptions): ServiceSchema[]
	}

```

This also will solve the Travis-ci problem;

**Comment by icebob** [comment]
@Wallacy the `ActionCatalogListOptions ` correct, but I don't like to define more detail of the `ServiceRegistry` because it's an internal class, and the methods are changing sometimes.

**Comment by Wallacy** [comment]
So, in this case better just keep only:

```javascript
{onlyLocal = false, onlyAvailable = false, skipInternal = false, withEndpoints = false}
```
From: https://github.com/moleculerjs/moleculer/blob/master/src/registry/action-catalog.js#L122

**Comment by Wallacy** [comment]
@icebob This was done on #735 too btw;

**Comment by icebob** [comment]
Great, thanks!

**Pull request closed without merging**
