### PR TITLE
[issue1042] Events when an error occured inside ServiceBroker #1042

### LINKED ISSUE #1042: Events when an error occured inside ServiceBroker
## Describe the solution you'd like
Many developers use error tracker modules like Sentry. But inside core modules errors would happen in many places that are handled and can't be redirected to error trackers (e.g. transporter/cacher disconnected, transit can't send a packet or received packet is invalid, ...etc).

To solve it, we should trigger local events (`broadcastLocal`) when a handled error is thrown.

- [ ] `$transporter.error`
- [ ] `$broker.error`
- [ ] `$transit.error`
- [ ] `$cacher.error`
- [ ] `$discoverer.error`

The error payload should looks like:
```js
{
  "error": "<the error object with all properties>"
  "module": "transporter" // Name of the module where the error happened
  "type": "disconnected" // Type of error.
}
```

## After that
1. Developer can create a sentry service which subscribes to local error events. E.g
  ```js
  module.exports = {
      name: "error-tracker",
  
      events: {
          "$**.error": {
              handler(ctx) {
                  // Send the error to the tracker
                  this.sendError(ctx.params.error);
              }
          }
      }
  }
  ```
2. Or subscribe to the events via `broker.localBus` in moleculer.config.js
```js
module.exports = {
    created(broker) {
        broker.localBus.on("*.error", payload => {
            // Send the error to the tracker
            this.sendError(payload.error);
        });
    }
}
```

### PR DESCRIPTION
**Pull request by AndreMaz**
### :dart: Relevant issues

Closes #1042 

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by intech** [comment]
Great job!

I think that the types of events should be placed in a [separate file with constants](https://github.com/moleculerjs/moleculer/blob/master/src/constants.js).

**Review by icebob — CHANGES_REQUESTED** [review]
Awesome job, thanks @AndreMaz
By the way, I agree with @intech that would be good to add error types to the constants file. Could you make it, as well?

**Comment by AndreMaz** [comment]
@icebob done 😉  @intech thank you for the suggestion 👍

**Comment by icebob** [comment]
Great, thanks!

**Pull request merged**
