### PR TITLE
fix issue#807

### PR DESCRIPTION
**Pull request by intech**
### :dart: Relevant issues
https://github.com/moleculerjs/moleculer/issues/807

### :gem: Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js
broker.createService({
    name: "test",
    settings: {
      test: 16384n
    }
});
``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] (utils.spec.js) Test utils.safetyObject -> should return a same object with BigInt

## :checkered_flag: Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [X] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by icebob — CHANGES_REQUESTED** [review]
Plz add relevant tests, as well.

**Comment by intech** [comment]
> Plz add relevant tests, as well.

Done.

**Comment by icebob** [comment]
https://travis-ci.org/github/moleculerjs/moleculer/jobs/724146972

**Comment by intech** [comment]
@icebob I took a closer look at the code, the `circularReplacer` method is only used in `safetyObject`. The `safetyObject` method only does the removal of recursions in the object.
Do you have any ideas how to solve this problem of using `BigInt` without native support in `JSON.parse` and `JSON.stringify` or should it be abandoned in settings?

**Comment by icebob** [comment]
MsgPack/Notepack serializer supports the BigInt?

**Comment by intech** [comment]
> MsgPack/Notepack serializer supports the BigInt?

No, only protobuf and [avsc](https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types)

**Pull request closed without merging**
