### PR TITLE
Update redis.js

### PR DESCRIPTION
**Pull request by Infinity0106**
line 191, 

## :memo: Description

stream of data returns array of matching keys instead of string, the client.del only accepts string instead of array.

### :dart: Relevant issues

The error that was throwing was 
`Redis 'scanDel' error. Pattern: MOL-users.* { ReplyError: ERR wrong number of arguments for 'del' command`

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by icebob** [comment]
Please:
- [ ] update tests
- [ ] don't reformat the codes, just push the modified code parts.

**Comment by Infinity0106** [comment]
my bad I discover that was my redis-server error

**Comment by iamdharmesh** [comment]
@Infinity0106 can you please share what was the error with redis-server? I am experiencing this same Error.

Thanks,
Dharmesh Patel

**Comment by Infinity0106** [comment]
I never figure it out what was the problem but when I started using it with redis the first time it always crashed on delete then I made a fix in my moleculer files, with the following info and then I got it working but after that removed moleculer and installing it again without my changes and it worked, I believe that it is the first run

**Pull request closed without merging**
