### PR TITLE
Remove usage of _.random

### PR DESCRIPTION
**Pull request by MrDroid1**
### :dart: Relevant issues

[issue:749](https://github.com/moleculerjs/moleculer/issues/749)

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by intech** [comment]
This is some automatically generated pull request, and it breaks the code.

**Comment by MrDroid1** [comment]
> This is some automatically generated pull request, and it breaks the code.

May you explain? I can't understend how does it break the code.

**Comment by intech** [comment]
@MrDroid1 Sorry, I rushed the review. I looked at the title of the pull request about replacing `lodash.random` and saw that you are removing parts of code not related to `lodash`, while `lodash` itself remains connected. I thought someone decided to play with chatgpt :)

Now I looked more closely and realized that you refactored not only related to the `random` method.

**Review by icebob — APPROVED** [review]
Good job, thanks!

**Pull request merged**
