### PR TITLE
Address feature request #344 to use '/' instead of '.' as MQTT topic separator. 

### PR DESCRIPTION
**Pull request by nmarus**
## :memo: Description

When using MQTT transport with RabbitMQ and the RabbitMQ MQTT Plugin, all dots get converted to slashes and vice versa. As such, nodes on this transport are not able to see each other as the topics are seen with slashes if published with dots.

From: https://www.rabbitmq.com/mqtt.html

> Note that MQTT uses slashes ("/") for topic segment separators and AMQP 0-9-1 uses dots. This plugin translates patterns under the hood to bridge the two, for example, cities/london becomes cities.london and vice versa. This has one important limitation: MQTT topics that have dots in them won't work as expected and are to be avoided, the same goes for AMQP 0-9-1 routing keys that contains slahes.

### :dart: Relevant issues
#344

### :gem: Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Not sure if this is a breaking change. Would depend on people that may use '.' in the namespace perhaps...

### :scroll: Example code
No user facing code changes. This only changes the format of topic generation for publish and subscribe when using a MQTT transport. 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Updated unit tests to validate '/' instead of '.'
- [x] Implemented this fork in a semi production application that uses a Rabbit MQ Cluster with the Rabbit MQ MQTT Plugin installed.

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by nmarus** [comment]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349375

**Comment by nmarus** [comment]
I can do that, but can you elaborate? The change I thought* I made was isolated to just the MQTT transporter. Mainly to override the `getTopicName` function in the MQTT transporter class that extends the BaseTransporter for use by MQTT publish and the on message event. This leaves the default as '.' for all other transporters that also extend BaseTransporter.

**Comment by nmarus** [comment]
@icebob Any updates on my question? After looking closer over the past few days, I still can't quite understand where making this a global config that changes to the class that mqtt.js extends is more ideal than just changing how only the mqtt transporter operates. The change I have submitted only effects mqtt transporter and also makes molecular compliant with the standards of the topic separator for mqtt protocol in the link I posted above as well.

**Comment by icebob** [comment]
Please wait, because I'm working on it right now. Sorry

**Comment by icebob** [comment]
Merged with https://github.com/moleculerjs/moleculer/commit/dfc7c73e3ceb69752e36c3179b2d52c4345923ba
Thanks

**Pull request closed without merging**
