### PR TITLE
Load es6 modules and changing service schema load checker.

### PR DESCRIPTION
**Pull request by Wallacy**
### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Comments 

This is linked to #337 and #328

I came up with this problem in my personal project, and that was the solution I found (with the @rhrn tip)

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Full: service-broker.spec
- [x] Added: "should load es6 module class service"
- [x] Changed: "should load 6 services"

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] **I have added tests that prove my fix is effective or that my feature works**
- [x] **New and existing unit tests pass locally with my changes**
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Wallacy** [comment]
For some reason travis-ci does not run the updated test.

**Comment by icebob** [comment]
Thanks for the PR, nevertheless, I don't think so that `esm` is necessary for Moleculer. Currently the `schema.default` checking is enough.

**Comment by Wallacy** [comment]
I think jest is not fully compatible with esm yet! jest.mock("../../../src/transporters/tcp/tcp-reader") is producing another module without all required properties for esm.

**Comment by Wallacy** [comment]
Without esm (or babel) moleculer will not load es6 modules because require will not parse "import * from Y".

https://nodejs.org/api/esm.html

Anyway, i think will be more wise to use babel directly instead esm.

**Comment by Wallacy** [comment]
I will make another PR to handle the problem separately.

**Comment by icebob** [comment]
OK

**Pull request closed without merging**
