### PR TITLE
implement a ctx.mcall method for #247

### PR DESCRIPTION
**Pull request by Leestex**
## :memo: Description

Implemented a `ctx.mcall` method, so it can be used to pass meta.

### :dart: Relevant issues
#247 meta is not passed when using mcall

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### :scroll: Example code
```js
ctx.mcall([
  { action: 'posts.find', params: { author: 1 } },
  { action: 'users.find', params: { name: 'Nazar' } }
], {
  meta: { token: '63f20c2d-8902-4d86-ad87-b58c9e2333c2' }
})
```

### CODE REVIEW

**Comment by Leestex** [comment]
@icebob thanks

Do you mean this one? https://github.com/moleculerjs/moleculer/pull/597/files#diff-75247703b0bdd0d557eaca3b6962f216R1193

Already did it. Please make sure it works as you expect it to be.

**Comment by Leestex** [comment]
I mean, my implementation should work for both cases: individual options for each action call, as well as a joint one passed as a second parameter to ctx.mcall

**Comment by icebob** [comment]
Ohh, sorry, I didn't see it. I've watched the tests, but I didn't see test case with this individual options. Could you add to the tests, as well?

**Comment by Leestex** [comment]
Sure, I will. Also, probably we should add it to the docs (website).

**Comment by icebob** [comment]
Yes, this is the next thing what I want to ask from you :) Could you help with the docs, as well? Btw as I see, the `mcall` is totally missed in the docs?!?!

**Comment by Leestex** [comment]
Haha, sure, that's the next thing I will do ;)

There is a mention of broker.mcall here https://moleculer.services/docs/0.13/broker.html#Methods

**Comment by icebob** [comment]
Oops, sorry, I've touched the context file and test, I hope you won't be merge conflict.

**Comment by icebob** [comment]
When could you add missing options tests?

**Comment by Leestex** [comment]
@icebob will do it tonight

**Comment by icebob** [comment]
Any updates?

**Pull request merged**
